# Generated by Django 3.0.2 on 2020-01-19 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.DecimalField(decimal_places=0, max_digits=1000, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Word')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Frequency of Word in Document')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Document')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.Word')),
            ],
        ),
    ]
